### ISSUE TITLE
Simulating TPM

### ISSUE THREAD

**Issue by riccardobecker** [Azure/azure-iot-connected-service#11]
Hi all,

does any of you have any experience and success with using a TPM simulator for integration and regression testing of devices? I want to achieve that I can run my tests in the cloud without having a true hardware module but only making use of the software tpm bits and a "TPM simulator".

Obviously, connecting to the IoT hub from a real device (dragonboard) containing a TPM module works fine.

Thanks in advance

**Comment by arturl** [comment]
Hi @riccardobecker,

Sorry for delayed response. We've tested it with both real TPM and TPM simulator, and it works identically. The extension doesn't see the difference.
