### ISSUE TITLE
Sending message to IOT HUB with TPM does throw an exception

### ISSUE THREAD

**Issue by levalencia** [Azure/azure-iot-connected-service#12]
We had our code with our hardcoded deviceky and url to create the deviceClient object and it was working fine, when we changed it to TPM according to this github repo readme, we get this issue:

http://stackoverflow.com/questions/40290568/object-reference-not-set-to-an-instance-of-an-object-when-sending-messages-with

We changed it back to the old way and now its working again, so looks like there is an ISSUE with TPM.

**Comment by arturl** [comment]
This is an issue with the SDK, not the extension: https://github.com/Azure/azure-iot-sdks/issues/842#issuecomment-264708885
