### ISSUE TITLE
Simulating TPM on Raspberry 3 results in only deviceId being pulled out from TPM device 

### ISSUE THREAD

**Issue by mslot** [Azure/azure-iot-connected-service#18]
Windows IoT v.10.0.16299.19
Raspberry Pi 3
TPM from: | MSFT - TPM Simulator
Type: | Emulator(NoSecurity)
Family: | 2.0
Revision: | 1.38
Firmware: | 8215.531.17.21504

I have provisioned the device successfully from the IoT Dashboard, and this is what I see when opening the TPM settings page

![image](https://user-images.githubusercontent.com/544655/32123403-5206a594-bb64-11e7-904f-77aaddf19319.png)

When i deploy my background task, it fails to retrieve all info from the TmpDevice but the device id. I am seeing this (including the portion of code doing the setup of the client:

![image](https://user-images.githubusercontent.com/544655/32124038-b87df9b0-bb66-11e7-9b91-b917ddfcc978.png)

I get an error because the sasToken is empty (obviously). Shouldnt I have gotten hostname, and sas token from the tmp device? Am I missing something obvious? Or is there a bug somewhere?

I have followed this write up: https://github.com/Azure/azure-iot-hub-vs-cs/wiki/Device-Provisioning-with-TPM

**Comment by kalyanb9119** [comment]
Try adding different capabilities in your package.appxmanifest file..  I have added everything.. it works.. 

<Capabilities>
    <Capability Name="internetClient" />
    <Capability Name="codeGeneration" />
    <Capability Name="allJoyn" />
    <Capability Name="internetClientServer" />
    <Capability Name="privateNetworkClientServer" />
    <iot:Capability Name="lowLevelDevices" />
    <uap:Capability Name="removableStorage" />
    <uap3:Capability Name="remoteSystem" />
    <uap:Capability Name="musicLibrary" />
    <uap:Capability Name="chat" />
    <uap:Capability Name="blockedChatMessages" />
    <uap3:Capability Name="backgroundMediaPlayback" />
    <uap:Capability Name="appointments" />
    <uap:Capability Name="contacts" />
    <uap:Capability Name="enterpriseAuthentication" />
    <uap:Capability Name="objects3D" />
    <uap:Capability Name="phoneCall" />
    <uap2:Capability Name="phoneCallHistoryPublic" />
    <uap:Capability Name="picturesLibrary" />
    <mobile:Capability Name="recordedCallsFolder" />
    <uap:Capability Name="sharedUserCertificates" />
    <uap2:Capability Name="spatialPerception" />
    <iot:Capability Name="systemManagement" />
    <uap:Capability Name="userAccountInformation" />
    <uap:Capability Name="videosLibrary" />
    <uap:Capability Name="voipCall" />
    <DeviceCapability Name="bluetooth" />
    <DeviceCapability Name="location" />
    <DeviceCapability Name="microphone" />
    <DeviceCapability Name="pointOfService" />
    <DeviceCapability Name="proximity" />
    <DeviceCapability Name="webcam" />
    <DeviceCapability Name="serialcommunication">
      <Device Id="any">
        <Function Type="name:serialPort" />
      </Device>
    </DeviceCapability>
  </Capabilities>

**Comment by mpoeckl** [comment]
@kalyanb9119 : that worked for me as well!
