### ISSUE TITLE
Add Transient Fault Handling in case of throttling

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/azure-iot-connected-service#2]
The generated code is currently using the HTTP1 protocol. As stated in https://azure.microsoft.com/nl-nl/documentation/articles/iot-hub-csharp-csharp-c2d/ , this is a protocol which can trigger Azure throttling. Please add transient fault handling as a best practice.

**Comment by arturl** [comment]
@sandervandevelde: thanks for the feedback. At this moment, only HTTP protocol is supported for UWP apps, but we're working on other protocols now. We can switch to AMQP or MQTT for non-UWP projects though, we'll consider it for the next release.

**Comment by arturl** [comment]
This is now solved by using AMQP as the default protocol.
