### ISSUE TITLE
Error 400 when trying to add an IoT Hub

### ISSUE THREAD

**Issue by dgkanatsios** [Azure/azure-iot-connected-service#3]
Currently trying to add IoT Hub, get error 400. Only 'weird' is that my account is associated with more than 1 subscriptions.
![capture](https://cloud.githubusercontent.com/assets/8256138/13613676/cfbf53ee-e575-11e5-972c-613e62ab4a27.JPG)

**Comment by arturl** [comment]
Thanks for the report @dgkanatsios!

**Comment by arturl** [comment]
Fixed by https://github.com/Azure/azure-iot-hub-vs-cs/commit/46919359cbcb10e647cce2488bd2d36027d3f02a
