### ISSUE TITLE
Unable to sign in with Visual Studio Update 2

### ISSUE THREAD

**Issue by mkstephenson** [Azure/azure-iot-connected-service#5]
I have Visual Studio Update 2 and just installed the extension. However when attempting to log in I get the following message.

<img width="345" alt="2016-04-09" src="https://cloud.githubusercontent.com/assets/6311405/14404631/d1bb6826-fe7b-11e5-9744-703c6e4e1d12.png">

**Comment by arturl** [comment]
Thanks @mkstephenson, I'll take a look as soon as I can.

**Comment by arturl** [comment]
The missing method was in an old assembly. I updated the dependent NuGet packages (see https://github.com/Azure/azure-iot-hub-vs-cs/commit/cf56b3183f4b84fe69c6bf023aece7a3ecf2b0e0) which should fix this problem.

**Comment by arturl** [comment]
A new version of the VSIX (1.2) should publish within a day or two.
