### ISSUE TITLE
Don't ship the Microsoft.VisualStudio.ConnectedServices.dll with the extension

### ISSUE THREAD

**Issue by AlexEyler** [Azure/azure-iot-connected-service#7]
_Microsoft.VisualStudio.ConnectedServices.dll_ is included in the Connected Services extension (installed by default to VS, I believe). If you ship this extension with this DLL, Visual Studio could end up loading the DLL from your extension location which can cause issues (including VS throwing an InvalidMefCacheException).

Let me know if you have any questions (I'm on the VS Extensibility team and own VS MEF).

**Comment by arturl** [comment]
Fixed in 1.3 release, commit https://github.com/Azure/azure-iot-hub-vs-cs/commit/a16d81b5aaccdb4fdce943977188e34bf324d141.
